[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "python -m tgtg"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "tgtg-scanner" 